const wisata = [
  {
    name: "Pantai Lampu Satu",
    lat: -8.5066604,
    lon: 140.3742368,
    category: "pantai",
    desc: "Pantai dengan mercusuar ikonik dan pasir putih yang luas.",
    history: "Dikenal sejak era kolonial Belanda...",
    img: "https://lh3.googleusercontent.com/gps-cs-s/AB5caB9iIcp8WUCPjMwPYcdzrhjUNOhYX6tItgawoQNgT70GPBxfi0yhnXv6k440ah1QeRZoHC9jv6RXB1QI3ObQfV-sSjAqM6Qs16D_irF_NbLe5rFFhTTbw5pNsCqGCdkgLQKa1cc=w408-h275-k-no",
  },
  {
    name: "Taman Nasional Wasur",
    lat: -8.5241017,
    lon: 140.5434396,
    category: "taman",
    desc: "Taman nasional yang menjadi surga bagi flora dan fauna Papua.",
    history: "Diresmikan pada tahun 1990...",
    img: "https://lh3.googleusercontent.com/gps-cs-s/AB5caB8yPR7Ht2-n4u0p63ZcVmMm7A4ZmwiyVbkDCNktIkdki-2m_zaFkb5x2-iph18wWX4UZryRTeA8dCl2AmmLjNxIwrJNdDVsEGqXns45axn9vHRvZ_zUCJqh2EzzuD1kO5hKinqfaA=w408-h544-k-no",
  },
  {
    name: "Monumen Kapsul Waktu",
    lat: -8.5081694,
    lon: 140.4104213,
    category: "monumen",
    desc: "Monumen modern menyimpan kapsul waktu berisi mimpi anak bangsa.",
    history: "Diresmikan pada 2018...",
    img: "https://lh3.googleusercontent.com/p/AF1QipM8cAVwRjgsUvf9QvyOGUN--JrXlMRjyHgTjwMJ=w427-h240-k-no",
  },
  {
    name: "Pantai Onggaya",
    lat: -8.7025248,
    lon: 140.5382889,
    category: "pantai",
    desc: "Pantai yang menawarkan pemandangan laut yang tenang dan pasir putih.",
    history: "Pantai Onggaya dikenal oleh masyarakat lokal...",
    img: "https://lh3.googleusercontent.com/gps-cs-s/AB5caB_6SZmQVeokRjimN3LR8gh45pjT3UyAExdh_4cshdlhaLw4jUlneS0MScP1J_vkhJQBhbwqdiqnl-aWEuQBINf_16ByxaJQyfEhOM9P-Hmv9wMs2SZbKsGYte37j1DZ9FKs3ag=w488-h240-k-no",
  },
  {
    name: "Danau Rawa Biru",
    lat: -8.6752383,
    lon: 140.8515421,
    category: "danau",
    desc: "Danau alami dengan air berwarna biru yang menenangkan.",
    history: "Danau ini berada dalam kawasan konservasi...",
    img: "https://lh3.googleusercontent.com/gps-cs-s/AB5caB-RyMFW_DYGOEupPiUHJ4TemLzF7Ez7AfLnuG_rhzb9_4r6i6GapvclBRR8ARsx2RW8udhjvHcS8abs0TlIJ8Kn6iUutF0VV6ceHmwJ2s5UoK5ZQdyIDVSJMJNTNHyPVq_5zfy5=w408-h306-k-no",
  },
  {
    name: "Pulau Habe",
    lat: -8.2416676,
    lon: 139.4381333,
    category: "pulau",
    desc: "Pulau kecil dengan suasana tenang dan alam yang indah.",
    history: "Pulau ini dijadikan tempat persinggahan nelayan...",
    img: "https://lh3.googleusercontent.com/gps-cs-s/AB5caB_XlymftkA31acPuNdNjXdIfX4y8v5Gax2-25X_-2fTbAAtA5ctFQ9xExFCuiKn-jsCwE1-hFVwCuP-mYNd_ht5EnrenlauPHBtsgNWItmvHsGH_oJ0-wSJJ5h0nPf_MNeSouuq5w=w408-h725-k-no",
  },
  {
    name: "Lotus Garden",
    lat: -8.3982056,
    lon: 140.4211606,
    category: "taman",
    desc: "Taman yang terkenal dengan kolam teratai yang cantik.",
    history: "Dibangun sebagai proyek penghijauan kota...",
    img: "https://lh3.googleusercontent.com/gps-cs-s/AB5caB-36gtmJqdIjlbynEOLI_h6mzYE8AH1xU6OJ4BqqA0jKzX0-8hwIgBgaUkaXrU-qDoFyJC7lnltfWTU8Mf5P_5SbEfLB4eIDLW9RgDDMkpMo2lvsBBauwUxeWooXLlTQggkRwFMVA=w426-h240-k-no",
  },
  {
    name: "Tugu 0 Kilometer Merauke-Sabang",
    lat: -8.4278199,
    lon: 141.0134053,
    category: "monumen",
    desc: "Tugu yang menandai titik paling timur Indonesia.",
    history: "Simbol kebangsaan ini menunjukkan garis imajiner Indonesia...",
    img: "https://lh3.googleusercontent.com/gps-cs-s/AB5caB9OwTwiFNFdwg1PDFuPPwytdnl8ukz_j6KDa3fO45IH1dpFCEFLmKrSkFZdgtidn-3oNZZD3mfP90GDxSgapKQ9ik3wok18Eq7gg44gyMmvY3j6LLZgZuGkm07tyqHUm2CYzSj6ow=w408-h306-k-no",
  },
  {
    name: "Wisata 1.000 Musamus",
    lat: -8.2457031,
    lon: 140.3678509,
    category: "monumen",
    desc: "Area dengan ribuan sarang rayap alami yang unik.",
    history: "Musamus adalah sarang rayap tanah khas Merauke...",
    img: "https://lh3.googleusercontent.com/gps-cs-s/AB5caB8eZxep165gco8leqyCCy2BbOKssygO_loku3_crQtZwGS_IV4Z_PVfrnlBNKfKQK-Ui8wx8v1PN6J-qALdIpQwNnKa0eMvoQ00WcWFFy6Dv62YnCUoVDJVVOj1B5m9q9CqouK1kA=w426-h240-k-no",
  },
  {
    name: "Pantai Payum",
    lat: -8.5466595,
    lon: 140.4159883,
    category: "pantai",
    desc: "Pantai yang terletak di sebelah selatan Kota Merauke, dikenal sebagai tempat favorit untuk menikmati matahari terbenam.",
    history:
      "Pantai ini sering dijadikan tempat bersantai oleh warga lokal maupun pengunjung karena aksesnya yang mudah dari pusat kota.",
    img: "https://lh3.googleusercontent.com/gps-cs-s/AB5caB_8y_irS_YvrVWNJYrTsNESDfaR4SjxSgIi6wS_R4N_GEphf-IGsaAZ-k0zDW_la17EpEP-V1EoqelvJHmwaU5ZSaD6sxkl6DdrunuY5iqoXw-nbtF5N6irt8jwMAjHHpUW6ssRDA=w408-h272-k-no",
  },
  {
    name: "Tugu Papera",
    lat: -8.4823174,
    lon: 140.3880745,
    category: "monumen",
    desc: "Monumen ikonik sebagai simbol perjuangan Papua.",
    history:
      "Tugu ini dibangun untuk mengenang perjuangan rakyat Papua dalam mempertahankan kemerdekaan.",
    img: "https://lh3.googleusercontent.com/gps-cs-s/AB5caB880CbtRNx27gjmfECXBdUq5NMnrVXRoARLbXtClhDbPqEDCmadXJqNy_PBLeANsVI14UjsSkEZ6mCuPK-dT_A0maAuzVARaiA9EvEsxwZc29sOzJVZIy0Qq2WtpOzwGd2KMy9b-w=w424-h240-k-no",
  },
  {
    name: "Pantai Buti",
    lat: -8.5251817,
    lon: 140.3871835,
    category: "pantai",
    desc: "Pantai alami dengan pasir putih dan ombak yang tenang.",
    history: "Pantai ini menjadi destinasi favorit keluarga saat akhir pekan.",
    img: "https://lh3.googleusercontent.com/gps-cs-s/AB5caB_ekkeQ1okrTZGAmKDkipP4LWDaIDwq5_qp91aQqiuJydVxKwxjHLWX7B477TAKBBKyZAdbSSeLaVnljVJZ7ZS5K-tNfQCgCvfVuu4_iFR6FaEYzce_RwdhEBETUef6lPN7JXpR=w408-h725-k-no",
  },
  {
    name: "Flat Beach Samkai",
    lat: -8.525862,
    lon: 140.3921508,
    category: "pantai",
    desc: "Pantai datar dengan pemandangan luas dan spot fotografi menarik.",
    history:
      "Cocok untuk aktivitas fotografi, olahraga pantai, dan acara komunitas.",
    img: "https://lh3.googleusercontent.com/gps-cs-s/AB5caB_m5R39S2Lr9wkWAeS3J2biy7hg24AV6tBbTuIm5rongaxWK6KtpZ_U2btpCCvAVOXDZ0b3Fz3ipAcwxji3fQ7jK_dCDEu_OK06HjS3HiPB848yye-bmvuEqFUJa11NyVoGbsbr=w426-h240-k-no",
  },
  {
    name: "Tugu Libra",
    lat: -8.4947064,
    lon: 140.401335,
    category: "monumen",
    desc: "Monumen berbentuk simbol zodiak Libra di pusat kota.",
    history:
      "Dibangun sebagai ikon unik kawasan Merauke yang kerap dikunjungi wisatawan.",
    img: "https://lh3.googleusercontent.com/gps-cs-s/AB5caB9jH1UR3CFUcunPdpkcy0yqW4meP2uh8VrSi_-6lSnauNfT9Jw4wuZIB3SoR59-ocqGHs_XQ7u9_WWTRzcKh57I1HjfPBIWJniH5jvDcx6yT8w_SgSQzQw2yrD2KWiPPmrw193u=w408-h306-k-no",
  },
  {
    name: "Patung Kristus Raja Semesta Alam",
    lat: -8.5166101,
    lon: 140.4130312,
    category: "monumen",
    desc: "Patung Kristus yang berdiri megah di halaman gereja Katolik.",
    history:
      "Menjadi pusat ziarah dan simbol keagamaan umat Katolik di Merauke.",
    img: "https://lh3.googleusercontent.com/gps-cs-s/AB5caB_5l8P2QFIBC0SxMwoZle9FrHCLxpXbJsKtweXqUDGUqgPk9zZvPqW40dLlUtC718BYAaT5WGswJvQKXKtWYhaXROSxb241eb_niNuo6MSx0Qo_9DEwqTUN5vPN8u4jky3mQIgt=w408-h260-k-no",
  },
  {
    name: "Taman Satwa Yamai Atid",
    lat: -8.4829927,
    lon: 140.3905714,
    category: "taman",
    desc: "Kebun binatang mini dengan koleksi hewan khas Papua.",
    history:
      "Dikelola oleh masyarakat lokal sebagai tempat edukasi fauna endemik.",
    img: "https://lh3.googleusercontent.com/gps-cs-s/AB5caB9boeS7bRigGDPJlF7kUp1aqZmZtzsMpXDWBj4cYZ7uoITSxGwQBZ94Jr1f4-O3WcyLlIC4L7_EBa91deTy_rWdgLS_ldBbBJLTmi1pyAuB0OaWnMdE4n8d39dN10eruEgKZ7SGRg=w408-h306-k-no",
  },
  {
    name: "Pantai Domande",
    lat: -8.1743611,
    lon: 139.9747356,
    category: "pantai",
    desc: "Pantai eksotis dengan air jernih dan lingkungan asri.",
    history:
      "Pantai ini sering dijadikan tempat bersantai oleh warga lokal maupun pengunjung.",
    img: "https://lh3.googleusercontent.com/gps-cs-s/AB5caB817Bnj5MVLJzUqxOb7tAzlCBANCwTVpHyXeVrPce0NGQkKKyPLYLsLx8PfNSv6n0Nh_yXf3708pLtpBFHB0zB281rhFgctovdPcKYn198o83LDV_rDuOOFyrzVhiA_Hg5QUqOv=w408-h306-k-no",
  },
  {
    name: "Pantai Annasai",
    lat: -8.4136544,
    lon: 140.2672242,
    category: "pantai",
    desc: "Pantai eksotis dengan pasir putih dan lingkungan asri.",
    history:
      "Pantai ini sering dijadikan tempat bersantai oleh warga lokal maupun pengunjung di saat liburan bersama keluarga.",
    img: "https://lh3.googleusercontent.com/gps-cs-s/AB5caB-RNAdbJJysn40LPPPo8bqRp4VhluSc4j81sNBj83-0wk-WMmtwnIezc2rg9vUSQBgpajF7F8yUSBtnQe4fv4mYbZT-DjZyvV_5uA9WC7QpNgivNXIXWWR6m50ql84c-T3uOps=w408-h725-k-no",
  },
  {
    name: "Taman Mangrove Taman Wisata Wilayah (TWW)",
    lat: -8.475727,
    lon: 140.435052,
    category: "taman",
    desc: "Kawasan konservasi mangrove yang juga menjadi tempat wisata edukatif.",
    history: "Dikenal sebagai lokasi penelitian mangrove dan wisata ekologi.",
    img: "https://lh3.googleusercontent.com/gps-cs-s/AB5caB9o5i31Lp53tRKL4pc9uC1BbilDjW4FhGOK3pRp6gY8AK939qluxP0zw8gAeAmxRtAdbVl_2q6tRg4m40o2eUjV9Om3n-5VhJuIB5lDuUzADpaKVHoxR57aigRWFYW3s0kNJKsqww=w408-h306-k-no",
  },
  {
    name: "Kolam Parako",
    lat: -8.5319623,
    lon: 140.4731521,
    category: "taman",
    desc: "Kolam alami dengan suasana tenang dan udara segar di pinggiran kota Merauke.",
    history:
      "Kolam ini sering dijadikan tempat rekreasi keluarga serta kegiatan outbond oleh pelajar dan komunitas.",
    img: "https://lh3.googleusercontent.com/gps-cs-s/AB5caB8r9VZphXkhy3lzN9byHsDmWxiSVBd2Xe7UoVsfZPvl88GXHYsHOqFeeM980noCny0CKOt-_d3yI2STpwxIuV6X42qv-qRlZENUMaS5jiPAH14FNLCl4gbQH0Cbjb5xXPZWIE7e7g=w408-h306-k-no",
  },
  {
    name: "Taman Ser Kaliki",
    lat: -8.1329715,
    lon: 140.2415997,
    category: "taman",
    desc: "Taman kota yang rindang dengan fasilitas bermain anak dan jogging track.",
    history:
      "Menjadi salah satu ruang terbuka hijau yang sering dikunjungi masyarakat Merauke untuk bersantai.",
    img: "https://lh3.googleusercontent.com/gps-cs-s/AB5caB9nHfsKpiPKLshZl-U0jV7VG6lyUYg6Z_f1R2PhtFLEIP638hCk96nYL50JHKfir6XdI9erVgpNG_FvQBk3c0-t7eKeOF-TXznRajJ8CS97tJnYkWC_IV0X_CwGHvWMgmL49Ck5BA=w408-h905-k-no",
  },
  {
    name: "Tablem Country",
    lat: -8.2408218,
    lon: 140.7834118,
    category: "taman",
    desc: "Tempat wisata berbasis peternakan dan alam terbuka yang ramah keluarga.",
    history:
      "Mengusung konsep agrowisata, tempat ini juga menawarkan edukasi tentang hewan ternak dan pertanian modern.",
    img: "https://lh3.googleusercontent.com/gps-cs-s/AB5caB9Dh67doslKFcXmBgvhqJbGlBGE3YZ_k9oQYocBKH7bk7J7VmBXBuN-IlXZtw5lg6OrTVCKzp1SlO0pu_U2LxEHykmp5qEk50ZN4sUdlnheuPrN38nCclWCd5asHIc2H6pjrtG6Ww=w408-h305-k-no",
  },
  {
    name: "Oomen Garden",
    lat: -8.4813408,
    lon: 140.3900937,
    category: "taman",
    desc: "Taman pribadi yang dibuka untuk umum dengan koleksi tanaman tropis dan spot foto Instagramable.",
    history:
      "Awalnya merupakan taman hobi pribadi yang berkembang menjadi destinasi wisata karena antusiasme pengunjung.",
    img: "https://lh3.googleusercontent.com/gps-cs-s/AB5caB_sjsb636cvbqZGcyRkXlgpvwfZXLdmjRAO9XWRoV4guy2wFeK4mHH6jsjfiYbCSMJdMJQ3ZvvXjuilfkgiKGe4k40KonvU9zajDrVZF-2O-FmRyQAQO6DOgr0qz2b-S_osCzAl_g=w408-h306-k-no",
  },
];
